<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework Condition="'$(TargetFramework)' == ''">net10.0</TargetFramework>
    <RootNamespace>DancingGoat</RootNamespace>
    <UserSecretsId>79c858af-5444-4954-8d08-6592a961e82a</UserSecretsId>
    <SeparatedAdmin Condition="'$(SeparatedAdmin)' == ''">false</SeparatedAdmin>
    <NoWarn>$(NoWarn);KXE0004;KXE0006</NoWarn>
    <AdminOrgName>dancing-goat</AdminOrgName>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Admin\CustomApplication\**" />
    <Compile Remove="Admin\SQLBrowser\**" />
    <Content Remove="Admin\CustomApplication\**" />
    <Content Remove="Admin\SQLBrowser\**" />
    <EmbeddedResource Remove="Admin\CustomApplication\**" />
    <EmbeddedResource Remove="Admin\SQLBrowser\**" />
    <None Remove="Admin\CustomApplication\**" />
    <None Remove="Admin\SQLBrowser\**" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="App_Data\CMSModules\WebFarm\webfarm.sync" />
    <None Remove="Client\src\DownloadExportTableCellComponent.tsx" />
  </ItemGroup>
  <ItemGroup>
    <AdminClientPath Include="Client\dist\**">
      <ProjectName>reporting</ProjectName>
    </AdminClientPath>
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Client\node_modules\**" />
    <Content Remove="Client\node_modules\**" />
    <EmbeddedResource Remove="Client\node_modules\**" />
    <None Remove="Client\node_modules\**" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Admin\ReportingApplication\UIPage\ExportListing.cs" />
    <Compile Remove="Admin\ReportingApplication\UIPage\Properties\DownloadExportClientProperties.cs" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="app_offline.htm_" Condition="Exists('app_offline.htm_')" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
  <!-- Exclude administration parts from the compilation in live-site only deployment  -->
  <ItemGroup Condition="'$(SeparatedAdmin)' == 'true'">
    <Compile Remove="AdminComponents\**" />
  </ItemGroup>
  <PropertyGroup Condition="'$(SeparatedAdmin)' == 'true'">
    <DefineConstants>$(DefineConstants);SEPARATED_ADMIN</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="33.1.0" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.23.0" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="10.0.0" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="kentico.xperience.admin" Version="31.7.0" Condition="'$(SeparatedAdmin)' == 'false'" />
    <PackageReference Include="kentico.xperience.azurestorage" Version="31.7.0" />
    <PackageReference Include="kentico.xperience.cloud" Version="31.7.0" />
    <PackageReference Include="kentico.xperience.imageprocessing" Version="31.7.0" />
    <PackageReference Include="kentico.xperience.mjml" Version="31.7.0" />
    <PackageReference Include="kentico.xperience.webapp" Version="31.7.0" />
    <PackageReference Include="Microsoft.SqlServer.TransactSql.ScriptDom" Version="180.78.1" />
    <PackageReference Include="NPOI" Version="2.8.0" />
    <PackageReference Include="XperienceCommunity.SqlBrowser" Version="5.0.0" />
  </ItemGroup>
</Project>
